In [1]:
from classifiers import ClanLSTMbatch
import torch.nn
import torch
import numpy as np
import os

In [10]:
tmp = torch.ones((10,32,100))

In [23]:
model = ClanLSTMbatch(4, 10)

In [12]:
result, _ = model.lstm(tmp)

In [13]:
result.shape

torch.Size([10, 32, 200])

In [14]:
tmp1 = torch.ones((4,4))
tmp2 = torch.ones((4,4))
tmp2[:,-1] = 0

In [39]:
mask = torch.tensor([1,1,1,0])

In [40]:
result, _ = model.lstm(tmp1)

In [45]:
result * mask.unsqueeze(1)

tensor([[-0.1529, -0.0892, -0.1253, -0.0282,  0.4240, -0.2224,  0.3130, -0.0211],
        [-0.2215, -0.1344, -0.1874, -0.0371,  0.4237, -0.1978,  0.2979, -0.0224],
        [-0.2522, -0.1557, -0.2191, -0.0394,  0.4104, -0.1581,  0.2610, -0.0226],
        [-0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000,  0.0000, -0.0000]],
       grad_fn=<MulBackward0>)

In [51]:
tmp = torch.cat((tmp1.unsqueeze(0), tmp2.unsqueeze(0)))

In [52]:
tmp.shape

torch.Size([2, 4, 4])

In [75]:
mask = torch.tensor([[1,1,1,0], [0,0,1,1]], dtype=bool)

In [76]:
tmp_masked = tmp * mask.unsqueeze(2)

In [72]:
tmp_masked

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 0.],
         [1., 1., 1., 0.]]])

In [77]:
tmp[mask]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

In [66]:
a = torch.Tensor([1,2,3,4])
mask = torch.BoolTensor([False, False, True, True])
b = a * mask

b[mask]

tensor([3., 4.])

In [78]:
c = torch.tensor([1,1,0])
c = c.to(bool)